### PR TITLE
feat: add support for OCP 4.14

### PR DESCRIPTION
**Pull request by rajatagarwal-ibm**
### Description

Update OCP related modules to only support the following versions: 4.12, 4.13, 4.14

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — APPROVED** [review]

**Comment by rajatagarwal-ibm** [comment]
Need to skip upgrade test because of OCP version change

```
│ Error: Invalid value for variable
│ 
│   on main.tf line 153, in module "ocp_base":
│  153:   ocp_version          = var.ocp_version
│     ├────────────────
│     │ var.ocp_version is "4.14"
│ 
│ The specified ocp_version is not of the valid versions.
│ 
│ This was checked by the validation rule at ../../variables.tf:107,3-13.
╵}
```

**Pull request merged**
