### PR TITLE
Expose CheckClusterIngressHealthy to the pr_test.go

### PR DESCRIPTION
**Pull request by dishankkalra23**
### Description
This PR exposes CheckClusterIngressHealthy to the pr_test.go to know the ingress state of the cluster.

https://github.ibm.com/GoldenEye/issues/issues/10545

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Addition of getClusterIngress method to expose the ingress state of the cluster

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by dishankkalra23** [comment]
Screenshot 2024-09-16 at 9 06 25 AM

Seems like an issue in validation added. Similar error can be seen in ocp-all-inclusive as well. Looking into this error.

**Comment by dishankkalra23** [comment]
@toddgiguere Validation is now working properly. Can you please give a final review to this PR?

**Comment by dishankkalra23** [comment]
PR has been failing continuously due to an error. I will re-run it later to check if it gets rectify.

**Review by daniel-butler-irl — APPROVED** [review]

**Pull request merged**
