### PR TITLE
fix: modified logic to handle csi-driver addon issue.

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description

Issue reference: [Issue-508](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/508)

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

* Incorporated validation logic to consider empty tuple for cluster addons.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by toddgiguere — APPROVED** [review]

**Comment by imprateeksh** [comment]
Issue validation: 

### Validation 1
The logic alone was validated initially by passing the cluster which does not have any addons installed. And no error was seen: 
image
The error seen on top in the image is with the existing code but when added the changes done in the PR, **no error can be seen in the output**

### Validation 2
Another validation was done by provisioning the advanced example, manually removing `vpc-block-csi-driver` and then ran plan again.

Before and after add-on removal - 
image

**Terraform plan shows no change ; No error is seen too.**

```hcl
$ t plan           
module.ocp_base.data.ibm_iam_account_settings.iam_account_settings: Reading...
module.ocp_base.data.ibm_iam_auth_token.reset_api_key_tokendata: Reading...
module.resource_group.data.ibm_resource_group.existing_resource_group[0]: Reading...
module.ocp_base.data.ibm_iam_auth_token.reset_api_key_tokendata: Read complete after 0s [id=2024-10-03 20:52:25.907117 +0000 UTC]
module.ocp_base.data.ibm_iam_account_settings.iam_account_settings: Read complete after 1s [id=abac0df06b644a9cabc6e44f55b3880e]
module.resource_group.data.ibm_resource_group.existing_resource_group[0]: Read complete after 1s [id=4a82b292689847bbb97f4a7f101a57e2]
module.ocp_base.data.ibm_container_cluster_versions.cluster_versions: Reading...
module.ocp_base.null_resource.reset_api_key: Refreshing state... [id=4161952366552849280]
module.kp_all_inclusive.module.key_protect[0].ibm_resource_instance.key_protect_instance: Refreshing state... [id=crn:v1:bluemix:public:kms:jp-tok:a/abac0df06b644a9cabc6e44f55b3880e:6c70a972-899b-4b99-ad1a-fa4b9ce20319::]
module.ocp_base.module.cos_instance[0].ibm_resource_instance.cos_instance[0]: Refreshing state... [id=crn:v1:bluemix:public:cloud-object-storage:global:a/abac0df06b644a9cabc6e44f55b3880e:ad6dbacb-cb50-488e-81ac-56149438ce01::]
ibm_is_vpc.vpc: Refreshing state... [id=r022-6eb5a3fd-ac05-4847-bcfe-05256570cc46]
module.ocp_base.data.ibm_container_cluster_versions.cluster_versions: Read complete after 1s [id=2024-10-03 20:52:27.938628 +0000 UTC]
module.kp_all_inclusive.module.kms_key_rings["ocp"].ibm_kms_key_rings.key_ring: Refreshing state... [id=ocp:keyRing:crn:v1:bluemix:public:kms:jp-tok:a/abac0df06b644a9cabc6e44f55b3880e:6c70a972-899b-4b99-ad1a-fa4b9ce20319::]
module.kp_all_inclusive.module.key_protect[0].ibm_kms_instance_policies.key_protect_instance_policies: Refreshing state... [id=crn:v1:bluemix:public:kms:jp-tok:a/abac0df06b644a9cabc6e44f55b3880e:6c70a972-899b-4b99-ad1a-fa4b9ce20319::]
module.kp_all_inclusive.module.kms_keys["ocp.ps1-test-cluster-data-encryption-key"].ibm_kms_key.key: Refreshing state... [id=crn:v1:bluemix:public:kms:jp-tok:a/abac0df06b644a9cabc6e44f55b3880e:6c70a972-899b-4b99-ad1a-fa4b9ce20319:key:94ff8f64-72e4-4ec4-9cbc-8d3347918cc9]
module.kp_all_inclusive.module.kms_keys["ocp.ps1-test-boot-volume-encryption-key"].ibm_kms_key.key: Refreshing state... [id=crn:v1:bluemix:public:kms:jp-tok:a/abac0df06b644a9cabc6e44f55b3880e:6c70a972-899b-4b99-ad1a-fa4b9ce20319:key:69691aea-1f94-41be-8c7c-d75b1fec4905]
module.kp_all_inclusive.module.kms_keys["ocp.ps1-test-cluster-data-encryption-key"].ibm_kms_key_policies.root_key_policy[0]: Refreshing state... [id=crn:v1:bluemix:public:kms:jp-tok:a/abac0df06b644a9cabc6e44f55b3880e:6c70a972-899b-4b99-ad1a-fa4b9ce20319:key:94ff8f64-72e4-4ec4-9cbc-8d3347918cc9]
module.kp_all_inclusive.module.kms_keys["ocp.ps1-test-boot-volume-encryption-key"].ibm_kms_key_policies.root_key_policy[0]: Refreshing state... [id=crn:v1:bluemix:public:kms:jp-tok:a/abac0df06b644a9cabc6e44f55b3880e:6c70a972-899b-4b99-ad1a-fa4b9ce20319:key:69691aea-1f94-41be-8c7c-d75b1fec4905]
ibm_is_public_gateway.gateway["1"]: Refreshing state... [id=r022-d6f32d52-d7ba-4175-b9d2-09983130df39]
ibm_is_public_gateway.gateway["3"]: Refreshing state... [id=r022-8a728a18-3015-4875-9a11-ce85b52e429b]
ibm_is_public_gateway.gateway["2"]: Refreshing state... [id=r022-5fa79a2f-01d6-4335-8965-f77c83557127]
ibm_is_subnet.subnets["2"]: Refreshing state... [id=02f7-eaf6f1a8-5505-4303-96c5-a8cf52bb91f2]
ibm_is_subnet.subnets["1"]: Refreshing state... [id=02e7-cc9c321c-0f55-4506-9586-870b5390e9f2]
ibm_is_subnet.subnets["3"]: Refreshing state... [id=02g7-c75e4e2a-bb35-4f62-868b-a499b4acc432]
module.ocp_base.ibm_container_vpc_cluster.autoscaling_cluster[0]: Refreshing state... [id=crvf087t0670q9aeqkug]
module.ocp_base.data.ibm_container_cluster_config.cluster_config[0]: Reading...
module.ocp_base.data.ibm_container_addons.existing_addons: Reading...
module.ocp_base.ibm_container_vpc_worker_pool.autoscaling_pool["default"]: Refreshing state... [id=crvf087t0670q9aeqkug/crvf087t0670q9aeqkug-db46cec]
module.ocp_base.ibm_container_vpc_worker_pool.autoscaling_pool["zone-3"]: Refreshing state... [id=crvf087t0670q9aeqkug/crvf087t0670q9aeqkug-e289609]
module.ocp_base.ibm_container_vpc_worker_pool.autoscaling_pool["zone-2"]: Refreshing state... [id=crvf087t0670q9aeqkug/crvf087t0670q9aeqkug-37385ad]
module.ocp_base.data.ibm_container_addons.existing_addons: Read complete after 2s [id=crvf087t0670q9aeqkug]
module.ocp_base.data.ibm_container_vpc_worker_pool.all_pools["zone-3"]: Reading...
module.ocp_base.data.ibm_container_vpc_worker_pool.all_pools["default"]: Reading...
module.ocp_base.data.ibm_container_vpc_worker_pool.all_pools["zone-2"]: Reading...
module.ocp_base.data.ibm_container_cluster_config.cluster_config[0]: Read complete after 6s [id=crvf087t0670q9aeqkug]
module.ocp_base.null_resource.confirm_network_healthy[0]: Refreshing state... [id=7558145881289026500]
module.ocp_base.ibm_container_addons.addons: Refreshing state... [id=crvf087t0670q9aeqkug]
module.ocp_base.data.ibm_iam_auth_token.tokendata: Reading...
data.ibm_container_cluster_config.cluster_config: Reading...
module.ocp_base.data.ibm_iam_auth_token.tokendata: Read complete after 0s [id=2024-10-03 20:52:53.1753 +0000 UTC]
module.ocp_base.data.ibm_container_vpc_worker_pool.all_pools["zone-3"]: Read complete after 2s [id=crvf087t0670q9aeqkug-e289609]
module.ocp_base.data.ibm_container_vpc_worker_pool.all_pools["default"]: Read complete after 2s [id=crvf087t0670q9aeqkug-db46cec]
module.ocp_base.data.ibm_container_vpc_worker_pool.all_pools["zone-2"]: Read complete after 2s [id=crvf087t0670q9aeqkug-37385ad]
module.ocp_base.null_resource.config_map_status[0]: Refreshing state... [id=4595174365866139334]
data.ibm_container_cluster_config.cluster_config: Read complete after 6s [id=crvf087t0670q9aeqkug]
module.ocp_base.kubernetes_config_map_v1_data.set_autoscaling[0]: Refreshing state... [id=kube-system/iks-ca-configmap]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
╷
│ Warning: Argument is deprecated
│ 
│   with module.kp_all_inclusive.module.kms_key_rings["ocp"].ibm_kms_key_rings.key_ring,
│   on .terraform/modules/kp_all_inclusive.kms_key_rings/main.tf line 9, in resource "ibm_kms_key_rings" "key_ring":
│    9:   force_delete  = var.force_delete
│ 
│ force_delete is now deprecated. Please remove all references to this field.
```

**Comment by ocofaigh** [comment]
Failed with:
```
│ Error: ---
│ id: terraform-97bab782
│ summary: 'Post "https://tags.global-search-tagging.cloud.ibm.com/v3/tags/attach?tag_type=access":
│   context deadline exceeded'
│ severity: error
│ resource: ibm_resource_tag
│ operation: create
│ component:
│   name: github.com/IBM-Cloud/terraform-provider-ibm
│   version: 1.70.1
│ ---
│ 
│ 
│   with module.ocp_base.ibm_resource_tag.cos_access_tag[0],
│   on ../../main.tf line 104, in resource "ibm_resource_tag" "cos_access_tag":
│  104: resource "ibm_resource_tag" "cos_access_tag" {
│ 
```

Unrelated to code in this Pr, so re-running..

**Pull request merged**
