### PR TITLE
doc: updated outbound traffic information for operator hub access

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description
Issue: [10133](https://github.ibm.com/GoldenEye/issues/issues/10133)

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [x] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@imprateeksh Thinking about this more, perhaps we do set `disable_outbound_traffic_protection` to `true` in the basic example (add a code comment to explaining what it does, or pointing to relevant IKS docs) and update the title of this example to `Basic single zone cluster with allowed outbound traffic`

**Comment by imprateeksh** [comment]
> @imprateeksh Thinking about this more, perhaps we do set `disable_outbound_traffic_protection` to `true` in the basic example (add a code comment to explaining what it does, or pointing to relevant IKS docs) and update the title of this example to `Basic single zone cluster with allowed outbound traffic`

Hi @ocofaigh - In basic example, currently we are not setting `disable_outbound_traffic_protection` as `true` and it picks up the default value which is `false`. This can be seen [here](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/0b9ab5e2019b0230ee39678d223add5e3ec606c1/examples/basic/main.tf#L70) and unlike other versions, [the value](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/0b9ab5e2019b0230ee39678d223add5e3ec606c1/main.tf#L46) is chosen from variable's [default value](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/0b9ab5e2019b0230ee39678d223add5e3ec606c1/variables.tf#L261).

**Comment by imprateeksh** [comment]
Basic example test is also successful. Logs from basic example (using OCP version 4.15) are shared here:
[output_test_basic_example.log](https://github.com/user-attachments/files/16943244/output_test_basic_example.log)

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
