### PR TITLE
fix: add count to the data block

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Added a count = var.verify_worker_network_readiness ? 1 : 0 on that data block and creating a private-only cluster in the apply_taints example which runs a test in the other_tests.
Ref: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/68#issuecomment-1479910490

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [x] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [x] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
Can we add a test for the new example please? Otherwise it will never be tested and could break at any time

**Comment by Aashiq-J** [comment]
I added the change to an existing example of apply_taints, it is being tested in the other_tests.
Should I move this to pr_test?

**Review by ocofaigh — APPROVED** [review]

**Comment by vburckhardt** [comment]
Probably fine for now - but we may want to change the name of the variable to "skip_connection_to_kube_master" as the data block is also used to force rbac sync https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/main/main.tf#L198

**Comment by vburckhardt** [comment]
Probably fine for now - but we may want to change the name of the variable to "skip_connection_to_kube_master" as the data block is also used to force rbac sync https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/blob/main/main.tf#L198

**Pull request merged**
