### PR TITLE
feat: add support to use  default ocp version

### PR DESCRIPTION
**Pull request by akocbek**
### Description

add support for default ocp version

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by ocofaigh** [comment]
@akocbek Pipeline failed with this `Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"9f60e66e-b1c0-42c4-9bd6-e360c26552a9","code":"E0035","description":"The requested container platform version is not available or not valid.","type":"Versions","recoveryCLI":"To list supported Kubernetes or OpenShift versions, run 'ibmcloud ks versions'."}`

Is it something you can reproduce locally?

**Comment by akocbek** [comment]
following the variable name "kube_version" I used `default_default_version`. Actually needs to be `default_openshift_version`. 
I renamed variable "kube_version" -> "ocp_version" to avoid confusion.

**Review by ocofaigh — CHANGES_REQUESTED** [review]
The description of the `ocp_version` variable needs to be updated to:

> The version of the OpenShift cluster that should be provisioned (format 4.x). This is only used during initial cluster provisioning, but ignored for future updates. Supports passing the string 'latest' (current latest available version) or 'default' (current IKS default recommended version). If no value is passed, it will default to 'default'.

Don't forget this is also needed in the fscloud submodule.

**Comment by akocbek** [comment]
changes in https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/256

**Pull request closed without merging**
