### PR TITLE
feat: add variable and option to not manage all addons

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

Added new input variable `manage_all_addons` (bool) and use value in the call to `ibm_container_addons` resource block. Default is `false` which tells Terraform to not manage addons that were not specifically installed using this module. If set to 'true' then addons installed outside this module may be destroyed on next apply.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

New input variable `manage_all_addons` (bool) has been added. 
Default is `false` which tells Terraform to not manage addons that were not specifically installed using this module. If set to 'true' then addons installed outside this module may be destroyed on next apply.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — APPROVED** [review]

**Comment by toddgiguere** [comment]
Upgrade test has failed, which I expected. There is only one consistency issue with the upgrade:
```
Resource(s) identified to be updated 
Name: addons
Address: module.ocp_base.ibm_container_addons.addons
Actions: [update]
DIFF:
  Before: 
 {"manage_all_addons":true}
  After: 
 {"manage_all_addons":false}
```
Since this was the only thing reported during upgrade, and it was expected, and it is just an update, I would recommend that we can skip the upgrade test on this PR.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
