### PR TITLE
fix(deps): update key-protect-all-inclusive to kms

### PR DESCRIPTION
**Pull request by MatthewLemmond**
### Description
Update the reference in the example for key-protect-all-inclusive to kms-all-inclusive

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by MatthewLemmond** [comment]
From https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/385, looks like the changes in that PR got overwritten and it was closed, example still using key-protect name so remade the PR

**Comment by ocofaigh** [comment]
A few errors:
```
Error: [0m Error: [ERROR] Error downloading the cluster config [cpgqnrhr0s0cbtktsl10]: Request failed with status code: 500, ServerErrorResponse: Error: lookup of user for "IAM:IBMid-666000KAO3" failed: useridentitymapping.user.openshift.io "IAM:IBMid-666000KAO3" not found
│ 
│   with module.ocp_base.data.ibm_container_cluster_config.cluster_config[0],
│   on ../../main.tf line 259, in data "ibm_container_cluster_config" "cluster_config":
│  259: data "ibm_container_cluster_config" "cluster_config" {
│ 
│ ---
│ id: terraform-82a5043b
Error: [0m summary: '[ERROR] Error downloading the cluster config
│ [cpgqnrhr0s0cbtktsl10]: Request
│   failed with status code: 500, ServerErrorResponse: Error: lookup of user for "IAM:IBMid-666000KAO3"
│   failed: useridentitymapping.user.openshift.io "IAM:IBMid-666000KAO3" not found'
│ severity: error
│ resource: (Data) ibm_container_cluster_config
│ operation: read
│ component:
│   name: github.com/IBM-Cloud/terraform-provider-ibm
│   version: 1.66.0
│ ---
│ 
╵
╷
Error: [0m Error: [ERROR] Error waiting for workerpool (cpgqnrhr0s0cbtktsl10/cpgqnrhr0s0cbtktsl10-46dbf63) to become ready: timeout while waiting for state to become 'deployed' (last state: 'provision_pending', timeout: 1h30m0s)
│ 
│   with module.ocp_base.ibm_container_vpc_worker_pool.autoscaling_pool["zone-3"],
│   on ../../main.tf line 326, in resource "ibm_container_vpc_worker_pool" "autoscaling_pool":
│  326: resource "ibm_container_vpc_worker_pool" "autoscaling_pool" {
│ 
│ ---
│ id: terraform-4b844566
Error: [0m summary: '[ERROR] Error waiting for workerpool
│ (cpgqnrhr0s0cbtktsl10/cpgqnrhr0s0cbtktsl10-46dbf63)
│   to become ready: timeout while waiting for state to become ''deployed'' (last state:
│   ''provision_pending'', timeout: 1h30m0s)'
│ severity: error
│ resource: ibm_container_vpc_worker_pool
│ operation: create
│ component:
│   name: github.com/IBM-Cloud/terraform-provider-ibm
│   version: 1.66.0
│ ---
│ 
╵}
```

Going to retry..

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
