### PR TITLE
feat: update description for ingress hostname

### PR DESCRIPTION
**Pull request by Khuzaima05**
### Description

updated the description for ingress hostname

issue: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/416

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by akocbek — APPROVED** [review]

**Comment by akocbek** [comment]
Do we have issue created for ?
> There is a separate ticket to change the output name https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5276 in provider. I think the module should change the name after the provider does to avoid confusion.

if not then I recommend to create it

**Review by ocofaigh — CHANGES_REQUESTED** [review]
Please make the change in `modules/fscloud/outputs.tf` too

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
