### PR TITLE
chore(example): created example to add rules in security groups

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description
Changes include :
 -  Addition of example to add rules to the `kube-<vpc-id>` and `kube-<cluster-id>` security groups.
 -  Making use of the `subnet_detail_map` from `terraform-ibm-landing-zone-vpc` module.

#### No release required

- [x] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [ ] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

### CODE REVIEW

**Review by toddgiguere — COMMENTED** [review]
I don't see any issues with any of this code, however I cannot tell if the example is valid just looking at terraform (might need further review), the test for the new example needs to be run locally to make sure it works (is not part of PR), and the change in the standard example to use subnets from VPC module, and not hard-coded, is going to make running the upgrade test tricky.

**Comment by ocofaigh** [comment]
Can we add the new example to pr_test.go ? Or at the very least add it to other_test.go so it gets tested once a week (when we add that support to the contonious test pipeline). If adding to other_test.go please show proof that test passed locally.

**Comment by imprateeksh** [comment]
> Can we add the new example to pr_test.go ? Or at the very least add it to other_test.go so it gets tested once a week (when we add that support to the contonious test pipeline). If adding to other_test.go please show proof that test passed locally.

Sure @ocofaigh , This newly created example was added as part of `other_tests.go`. Please find below the proof/result of all the test runs executed locally : 
[TestRunSzClusterExample.log](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/files/11072768/TestRunSzClusterExample.log)
[TestRunMultiClusterExample.log](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/files/11072771/TestRunMultiClusterExample.log)
[TestRunAddRulesToSGExample.log](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/files/11072772/TestRunAddRulesToSGExample.log) - Newly added example
[TestRunApplyTaintsExample.log](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/files/11072775/TestRunApplyTaintsExample.log)

**Comment by imprateeksh** [comment]
In pipeline, Standard Example worked fine 
image

Upgrade test is [failing](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/actions/runs/4542779270/jobs/8006634969?pr=72#step:7:4425):
image

 
Trying to resolve this issue.

**Comment by imprateeksh** [comment]
@ocofaigh - Due to multiple changes coming in this module the actual changes needed i.e. addition of example are not getting merged. I created another PR to add security rules example [here](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/110)
Also, attached the results and created test in `other_tests.go` .
This should pass without any issues and once done we can close the issue too and this PR can also be deleted once completed.

**Pull request closed without merging**
