### PR TITLE
feat: added support for ocp v4.16 

### PR DESCRIPTION
**Pull request by imprateeksh**
### Description

Refer Issue: [Issue-10665](https://github.ibm.com/GoldenEye/issues/issues/10665)

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

* Support added to include ocp version 4.16 

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by imprateeksh** [comment]
The test `TestRunUpgradeAdvancedExample` is [failing](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/actions/runs/11085882755/job/30802960776#step:7:1695) as the older version i.e. **current main** has no information about version `4.16` which is passed to upgrade test. Now we can: 
a) Either skip the upgrade test, or 
b) Instead of using version `4.16` for `TestRunUpgradeAdvancedExample`, can use version `4.15` and later revert to version to `4.16`  - Temporarily testing this and will revert once the tests are passed.

**Comment by imprateeksh** [comment]
Even the PR has passed but can see the error [here](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/actions/runs/11090508891/job/30812979074#step:7:3308) for `TestRunAdvancedExample` and [here](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/actions/runs/11090508891/job/30812979074#step:7:4830) for `TestRunUpgradeAdvancedExample` . Error is: 

image


This was also present in previous failed run too - Can be seen [here](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/actions/runs/11085882755/job/30802960776#step:7:2497)

**Comment by ocofaigh** [comment]
@imprateeksh That error is related to incorrect addresses being used in `ImplicitDestroy` in pr_test.go. It purposely does not fail pipeline - but we should probably try and fix it to remove the error from the logs. I created a follow up issue: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/536

**Pull request merged**
