### PR TITLE
mandate os input

### PR DESCRIPTION
**Pull request by Aayush-Abhyarthi**
### Description

https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/475

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

This PR mandates user to provide the operating system for additional worker pools.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by Aashiq-J — APPROVED** [review]
LGTM.

We will need to make changes in all the modules consuming the base-ocp
- https://github.ibm.com/GoldenEye/ocp-all-inclusive-module
- https://github.com/terraform-ibm-modules/terraform-ibm-ocp-all-inclusive
- https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/tree/main

**Review by ocofaigh — CHANGES_REQUESTED** [review]
The usage section in the readmes needs to be updated since `operating_system` is now required to be passed for the `worker_pools` input
image

**Review by ocofaigh — APPROVED** [review]

**Comment by vbontempi** [comment]
Wondering if setting a default value for the operating system (with the default value used when not specified before this change) would have been a less disruptive change for existing adopters

**Pull request merged**
