### PR TITLE
feat: update ocp_entitlement default value to null

### PR DESCRIPTION
**Pull request by Khuzaima05**
### Description
updated the ocp_entitlement default value to null

issue: https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/issues/446

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@Khuzaima05 We will need all our examples to be updated so the `ocp_entitlement` value can be passed into them. The default value for the examples should also be `null` however we should override this to `"cloud_pak"` in every test that executes the examples.

**Comment by Khuzaima05** [comment]
upgrade test is failing, so skipping it

Screenshot 2024-06-26 at 1 35 57 PM

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
