### PR TITLE
fix: update autoscaler version

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

Issue: https://github.ibm.com/GoldenEye/issues/issues/6967

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Aashiq-J** [comment]
@ocofaigh,
The `TestRunUpgradeAdvancedExample` upgrade test will fail because the main branch has the old cluster-autoscaler version and test uses the 4.14 version.

```
TestRunUpgradeAdvancedExample 2023-12-19T14:12:33Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: Request failed with status code: 400, ServerErrorResponse: {"incidentID":"5cb7b507-902f-4693-a017-1c4f112de8a4","code":"E3419","description":"The 'cluster-autoscaler' add-on is not
```

**Comment by ocofaigh** [comment]
Pipeline failed with `Error: [ERROR] Error deleting resource instance: Instance is in reclamation, please use the API to the delete the resource reclamation for the instance.` Unrelated to changes in this PR so retrying..

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
