### PR TITLE
fix: limit the terraform version

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Update the version of the csi-driver and set a upper limit on the terraform version.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- When merging, use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
- Merge by using "Squash and merge".

### CODE REVIEW

**Comment by Aashiq-J** [comment]
@ocofaigh, All the tests are passing except the upgrade test. I guess its okay to skip the upgrade test.
Screenshot 2023-10-09 at 3 16 32 PM

**Comment by ocofaigh** [comment]
@Aashiq-J Have we ever done an upgrade of an addon version? Can an addon even be upgraded once cluster is installed? What is the impact (if any)? Perhaps we need to manually try upgrade? Is it possible to do 5.1 -> 5.2, or does 5.1 also fail currently?

**Comment by Aashiq-J** [comment]
No, the addon was not updated. 
Will test the 5.1->5.2

**Comment by Aashiq-J** [comment]
Screenshot 2023-10-09 at 6 56 04 PM
When updating from 5.1 to 5.2, terraform identifies it as a change. We was able to update the driver to 5.2 without any issue.
So are we good to merge this PR?

**Review by ocofaigh — APPROVED** [review]

**Comment by ocofaigh** [comment]
Pipeline failed with `Error: InvalidRequest: Server Side Encryption with hs-crypto is not enabled.` which doesn't seem related to the changes in this PR, so re-running..

**Comment by jojustin** [comment]
This PR is already approved by Conall, and this is patch release.  So going ahead and merging this.

**Pull request merged**
