### PR TITLE
chore: update minimum provider version required to 1.66.0

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
Why are you doing this? The fix is already in main branch, and there is no need to update the required provider version?
PS: 1 further fix needed, and is coming in https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/455

**Comment by Aashiq-J** [comment]
This is fix the PR pipeline failure in this [renovate PR](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/pull/444)
With the update of the cos module, the minimum required ibm provider version is 1.66

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
