### PR TITLE
feat: add `wait_for_apply` option in `kms_config` object input variable

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

Undocumented feature which should address https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone/issues/747

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
The pipeline timed out after 3 hours so we may want to reconsider defaulting `wait_for_apply` to true if its going to take that long. I have extended the timeout to 5 hours to see if we can figure out exactly how long it will take though

**Comment by ocofaigh** [comment]
The timeout seen in previous error seems unrelated. The re-run took 41mins:
`module.ocp_base.ibm_container_vpc_cluster.autoscaling_cluster[0]: Creation complete after 41m27s [id=cp85nr9z06uja9vrao20]`

**Review by toddgiguere — APPROVED** [review]

**Pull request merged**
