### PR TITLE
feat: enable new endpoint type for cluster config

### PR DESCRIPTION
**Pull request by toddgiguere**
### Description

In order to fully support OCP 4.13 with disabled public endpoint, the IBM provider team has added a new parameter `endpoint_type` to the `ibm_container_cluster_config` data block to specify an endpoint type that may not be the default.

Added a new input parameter to provide the endpoint type to this module, and use this module in the `ibm_container_cluster_config` data block.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Added new input variable `cluster_config_endpoint_type` that will be passed into the new parameter `endpoint_type` for the `ibm_container_cluster_config` data block used in this module.

This change will allow you to specify a different endpoint for cluster configuration than the default, for instance if using OCP 4.13 with public endpoint disabled, and you do not want to use the default endpoint of VPE, you can now specify "private" to use the private endpoint.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by toddgiguere** [comment]
Standard test failed when downloading cluster config in base module:
```
"The cluster is not fully deployed yet. Wait a few minutes, then try again."
```

All other tests passed though, which also use same logic, so I'm assuming this is a one-off timing issue, and I'll run pipeline again

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
