### PR TITLE
Terraform Example Code Optimized not to be consumed directly

### PR DESCRIPTION
**Pull request by marifse**
### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by marifse** [comment]
@ocofaigh, @toddgiguere  can you please review this PR.

**Comment by marifse** [comment]
@ocofaigh can you please review it too. Thanks

**Comment by marifse** [comment]
@ocofaigh , sorry to bother you but can you please review this PR and approve it if all is okay.

**Comment by toddgiguere** [comment]
@marifse I noticed that many of the changes in this PR appear to be backing out some changes that probably exist in the main repo? I see a lot of versions of things being rolled back. Is that because your fork needs to be synced with latest?

**Comment by marifse** [comment]
> @marifse I noticed that many of the changes in this PR appear to be backing out some changes that probably exist in the main repo? I see a lot of versions of things being rolled back. Is that because your fork needs to be synced with latest?

@toddgiguere please check now, the fork has been synced with latest.

@ocofaigh please check and verify. Thanks

**Comment by marifse** [comment]
@ocofaigh can you please have a look, appreciated your time. thanks

**Review by ocofaigh — CHANGES_REQUESTED** [review]
You need to update the `TestFSCloudInSchematic` test since there are now more required variables. The test failed in pipeline with:

```
 2024/03/26 16:03:15 Terraform plan | Error: No value for required variable
 2024/03/26 16:03:15 Terraform plan | 
 2024/03/26 16:03:15 Terraform plan |   on variables.tf line 59:
 2024/03/26 16:03:15 Terraform plan |   59: variable "vpc_name" {
```

**Comment by ocofaigh** [comment]
@marifse Looks like you have an old version of common-dev-assets in your branch:
```
Check git submodule up to date...........................................Failed
- hook id: git-submodule-version-check
- exit code: 1

Current PR branch submodule version: cc55b9b98178d3aa3d7af8c4f3eae09e1bb83026
Submodule 'common-dev-assets' (https://github.com/terraform-ibm-modules/common-dev-assets) registered for path 'common-dev-assets'
Cloning into '/tmp/tmp.0I71XdglOw/terraform-ibm-base-ocp-vpc/common-dev-assets'...
Submodule path 'common-dev-assets': checked out '8405107509b351b346887674d06ee37e98140493'
Primary branch submodule version: 8405[107](https://github.com/terraform-ibm-modules/terraform-ibm-base-ocp-vpc/actions/runs/8480625938/job/23236682428#step:6:108)509b351b346887674d06ee37e98140493

Detected common-dev-assets git submodule commit ID is older than the one in primary branch. To fix:
  1. Record the current state of the working directory:
      i. git stash
  2. Ensure that your local primary branch is up to date:
      i. git checkout <master / main>
      ii. git pull origin <master / main>
      iii. git submodule update --rebase
  3. Make sure your dev branch is rebased with remote primary branch:
      i. git checkout <dev-branch>
      ii. git stash pop
      iii. git pull origin <master / main>
  4. Run the following command to sync the git submodule with primary branch:
      i. git submodule update --rebase

Alternatively you can run 'git submodule update --remote --merge' to update your branch to the latest available git submodule, however this is not recommended, as you will likely soon end up with conflicts to resolve due to the renovate automation that is updating the git submodule version in primary branch very frequently.
```

**Comment by marifse** [comment]
@ocofaigh please recheck now.

**Comment by ocofaigh** [comment]
@marifse 
image

**Comment by marifse** [comment]
@ocofaigh fixed, please re-run the pipeline.

**Pull request merged**
